apiVersion: apps/v1
kind: Deployment
metadata:
  name: sds-tracking-service
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: sds-tracking-service 
  template: 
    metadata: 
      labels: 
        app: sds-tracking-service
    spec: 
      imagePullSecrets:
      {{- if .Values.requiredSecrets.p44ImagePullSecret }}    
      - name: {{ .Values.requiredSecrets.p44ImagePullSecret }}
      {{- end }}

